apiVersion: apps/v1
kind: Deployment
metadata:
  name: meikao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meikao
  template:
    metadata:
      labels:
        app: meikao
    spec:
      containers:
      - image: okteto.dev/meikao:latest
        name: meikao
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vless_UUID
          value: "cd2b731f-c4bd-4114-b81f-f381e89f0414"
        - name: Vless_Path
          value: "/s2335"
        - name: Vmess_UUID
          value: "cd2b731f-c4bd-4114-b81f-f381e89f0414"
        - name: Vmess_Path
          value: "/s2446"
        - name: Share_Path
          value: "Shares2335"
