apiVersion: apps/v1
kind: Deployment
metadata:
  name: kao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kao
  template:
    metadata:
      labels:
        app: kao
    spec:
      containers:
      - image: okteto.dev/kao:latest
        name: kao
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "d2356074-81fa-40df-977d-d0e3df5c4dc0"
        - name: Vless_Path
          value: "/s2335"
        - name: Vmess_UUID
          value: "d2356074-81fa-40df-977d-d0e3df5c4dc0"
        - name: Vmess_Path
          value: "/s2446"
        - name: Share_Path
          value: "Shares2335"
